version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: rete11/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/
    depends_on:
      - db
  frontend:
    image: rete11/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: rete11/kittygram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80